### ISSUE TITLE
Current asset color doesn't apply after change

### ISSUE THREAD

**Issue by PVGrad** [g8extended/Character-Generator#18]
All other assets are changing colors, except current asset that is selected.
It should be fixed because if you want to check how current asset will look like in another color i'll need to do odd steps:
* change color
* arrow right
* arrow left

**Comment by eugeneglova** [comment]
![demo-character-3](https://cloud.githubusercontent.com/assets/2828226/23235353/4186a86a-f966-11e6-86ab-1f2c88bd2990.gif)

**Comment by eugeneglova** [comment]
fixed last bugs in https://github.com/g8extended/Character-Generator/pull/26
